$:
  vscode:
    - runner:
        cpus: 4
      docker:
        build: .ide/Dockerfile
      services:
        - vscode
        - docker
      stages:
        - name: 初始化完成
          script: echo "初始化完成"

.common_sync: &common_sync
  docker:
    build: .ide/Dockerfile
  imports:
    - https://cnb.cool/Mintimate/secret/-/blob/main/SyncToGitHub.yml

.common_git_steps: &common_git_steps
  name: 自动同步代码
  script:
    - git clone https://${GIT_PUBLIC_ACCESS_TOKEN}@github.com/Mintimate/oh-my-rime.git
    - cd oh-my-rime
    - git config user.name "github-actions"
    - git config user.email "github-actions[bot]@users.noreply.github.com"
    - cd ../

main:
  push:
    - name: "推送镜像"
      <<: *common_sync
      stages:
        - name: 自动同步代码
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Mintimate/rime-dict-sync.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            force: true
  "crontab: 15 10 29 * *":
    - name: "定时同步万象"
      <<: *common_sync
      stages:
        - name: 自动同步词库
          script: 
            - go mod tidy
            - go build .
            - bash syncWanxiang.sh
        - <<: *common_git_steps
        - name: 推送代码
          script:
            - cp dl_dicts/* oh-my-rime/dicts/
            - cd oh-my-rime && git add .
            - 'git commit -m "AutoUpdate Wanxiang pinyin Dicts" -m "" -m "Co-authored-by: amzxyz <129564993+amzxyz@users.noreply.github.com>"'
            - git push
  "crontab: 0 15 5 * *":
    - name: "定时同步拆字"
      <<: *common_sync
      stages:
        - name: 自动同步词库
          script: 
            - go mod tidy
            - go build .
            - bash syncRadical.sh
        - <<: *common_git_steps
        - name: 推送代码
          script:
            - cp dl_dicts/* oh-my-rime/
            - cd oh-my-rime && git add .
            - 'git commit -m "AutoUpdate Radical pinyin Dicts" -m "" -m "Co-authored-by: mirtlecn <76689045+mirtlecn@users.noreply.github.com>"'
            - git push