# 下载的词库，保存名称-下载地址
DOWNLOAD_DIR: "dl_dicts"
TARGET_DICT:
  - name: "radical_pinyin.dict.yaml"
    url: "https://github.com/mirtlecn/rime-radical-pinyin/raw/master/radical_pinyin.dict.yaml"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "radical_pinyin.dict.yaml"