# 下载的词库，保存名称-下载地址
DOWNLOAD_DIR: "dl_dicts"
TARGET_DICT:
  - name: "rime_ice.en.dict.yaml"
    url: "https://raw.githubusercontent.com/iDvel/rime-ice/main/en_dicts/en.dict.yaml"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_ice.en.dict.yaml"
    merge_mode: "keep_remote_header"
  - name: "rime_ice.en_ext.dict.yaml"
    url: "https://raw.githubusercontent.com/iDvel/rime-ice/main/en_dicts/en_ext.dict.yaml"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_ice.en_ext.dict.yaml"
    merge_mode: "keep_remote_header"
  - name: "rime_ice.cn_en.txt"
    url: "https://raw.githubusercontent.com/iDvel/rime-ice/main/en_dicts/cn_en.txt"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_ice.cn_en.txt"
    merge_mode: "keep_remote_header"
  - name: "rime_ice.cn_en_flypy.txt"
    url: "https://raw.githubusercontent.com/iDvel/rime-ice/main/en_dicts/cn_en_flypy.txt"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_ice.cn_en_flypy.txt"
    merge_mode: "keep_remote_header"
