# 下载的词库，保存名称-下载地址
DOWNLOAD_DIR: "dl_dicts"
TARGET_DICT:
  - name: "rime_mint.base.dict.yaml"
    url: "https://raw.githubusercontent.com/amzxyz/rime_wanxiang/refs/heads/wanxiang/dicts/jichu.dict.yaml"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_mint.base.dict.yaml"
  - name: "rime_mint.chars.dict.yaml"
    url: "https://raw.githubusercontent.com/amzxyz/rime_wanxiang/refs/heads/wanxiang/dicts/zi.dict.yaml"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_mint.chars.dict.yaml"
  - name: "rime_mint.correlation.dict.yaml"
    url: "https://raw.githubusercontent.com/amzxyz/rime_wanxiang/refs/heads/wanxiang/dicts/cuoyin.dict.yaml"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_mint.correlation.dict.yaml"
  - name: "rime_mint.ext.dict.yaml"
    url: "https://raw.githubusercontent.com/amzxyz/rime_wanxiang/refs/heads/wanxiang/dicts/lianxiang.dict.yaml"
    remote_repo: "https://github.com/Mintimate/oh-my-rime.git"
    remote_path: "dicts/rime_mint.ext.dict.yaml"
